package com.github.rewrite.ejb;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.java.JavaParser;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;
import org.openrewrite.test.TypeValidation;

import static org.openrewrite.java.Assertions.java;
import static org.openrewrite.test.SourceSpecs.text;

/**
 * Tests for MigrateScheduleToQuartz recipe.
 * <p>
 * This recipe performs AUTOMATIC transformation for @Schedule methods:
 * - Keeps original method (removes @Schedule, removes Timer parameter)
 * - Generates inner Job class with constructor injection (takes enclosing class as delegate)
 * - Generates nested @Configuration class (QuartzConfig) with @Bean methods for:
 *   - JobDetail (with FQN-based prefix to avoid collisions across packages)
 *   - Trigger(s) (with FQN-based prefix to avoid collisions across packages)
 * - Generates shared QuartzJobFactoryAutoConfiguration with JobFactory and SchedulerCustomizer
 *   via META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
 * - Multiple @Schedules → multiple Triggers
 * <p>
 * Falls back to @EjbQuartzSchedule marker only for unresolvable cases:
 * - Non-literal @Schedule values
 * - @Schedule with year or timezone attributes
 * - Timer API usage other than getInfo()
 */
class MigrateScheduleToQuartzTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        // ResolveTimerStrategy must run first to set the TimerStrategyMarker
        // based on code analysis (e.g., @Schedule with Timer parameter requires QUARTZ)
        spec.recipes(new ResolveTimerStrategy(), new MigrateScheduleToQuartz())
            .parser(JavaParser.fromJavaVersion()
                .classpath("jakarta.jakartaee-api", "spring-context", "spring-beans", "spring-boot-autoconfigure"))
            // Disable type validation since manually constructed AST nodes don't have type info
            .typeValidationOptions(TypeValidation.none());
    }

    // Expected generated files for tests with actual transformations
    private static final String EXPECTED_AUTO_CONFIG = """
            package com.github.migration.config;

            import org.quartz.Job;
            import org.quartz.Scheduler;
            import org.quartz.SchedulerException;
            import org.quartz.spi.JobFactory;
            import org.quartz.spi.TriggerFiredBundle;
            import org.springframework.beans.factory.config.AutowireCapableBeanFactory;
            import org.springframework.boot.autoconfigure.AutoConfiguration;
            import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
            import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
            import org.springframework.boot.autoconfigure.quartz.SchedulerFactoryBeanCustomizer;
            import org.springframework.context.annotation.Bean;

            /**
             * Auto-configuration for Quartz JobFactory with constructor injection support.
             * Generated by MigrateScheduleToQuartz recipe.
             * <p>
             * This configuration enables Quartz to instantiate Job classes using Spring's
             * AutowireCapableBeanFactory, which supports constructor injection.
             */
            @AutoConfiguration
            @ConditionalOnClass(Job.class)
            public class QuartzJobFactoryAutoConfiguration {

                @Bean
                @ConditionalOnMissingBean(JobFactory.class)
                public JobFactory quartzJobFactory(AutowireCapableBeanFactory beanFactory) {
                    return new JobFactory() {
                        @Override
                        public Job newJob(TriggerFiredBundle bundle, Scheduler scheduler) throws SchedulerException {
                            return beanFactory.createBean(bundle.getJobDetail().getJobClass());
                        }
                    };
                }

                @Bean
                @ConditionalOnMissingBean(SchedulerFactoryBeanCustomizer.class)
                public SchedulerFactoryBeanCustomizer schedulerCustomizer(JobFactory quartzJobFactory) {
                    return schedulerFactoryBean -> schedulerFactoryBean.setJobFactory(quartzJobFactory);
                }
            }
            """;

    private static final String EXPECTED_AUTO_CONFIG_IMPORTS = "com.github.migration.config.QuartzJobFactoryAutoConfiguration\n";

    @Test
    void skipsMethodWithoutScheduleAnnotation() {
        // Methods without @Schedule are not handled
        // ResolveTimerStrategy still adds marker (1 cycle) but no transformation occurs
        String input = """
                import jakarta.ejb.Timer;

                public class NoSchedule {
                    public void someMethod(Timer timer) {
                        timer.cancel();
                    }
                }
                """;
        rewriteRun(
            spec -> spec.expectedCyclesThatMakeChanges(1),
            java(input, input)  // Same input as output = no visible change expected
        );
    }

    @DocumentExample
    @Test
    void automaticallyTransformsScheduleWithTimerParameter() {
        // Basic case: @Schedule method with Timer parameter gets automatic transformation
        // Original method is kept (minus @Schedule and Timer param), Job delegates via constructor injection
        // timer.getInfo() without info attribute -> null
        rewriteRun(
            // ScanningRecipe with generate() needs 2 cycles when generating new files
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.ejb.Schedule;
                import jakarta.ejb.Timer;

                public class QuartzScheduler {
                    @Schedule(minute = "*/5", hour = "*")
                    public void scheduledTask(Timer timer) {
                        String info = (String) timer.getInfo();
                    }
                }
                """,
                """
                import org.quartz.*;
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;

                public class QuartzScheduler {
                    public void scheduledTask() {
                        String info = (String) null;
                    }

                    public static class ScheduledTaskJob implements Job {
                        private final QuartzScheduler delegate;

                        public ScheduledTaskJob(QuartzScheduler delegate) {
                            this.delegate = delegate;
                        }

                        @Override
                        public final void execute(JobExecutionContext context) throws JobExecutionException {
                            delegate.scheduledTask();
                        }
                    }

                    @Configuration
                    public static class QuartzConfig {

                        @Bean
                        public JobDetail quartzSchedulerScheduledTaskJobDetail() {
                        return
                            JobBuilder.newJob(ScheduledTaskJob.class).
                                withIdentity("quartzSchedulerScheduledTaskJobDetail").
                                storeDurably().
                                build();
                    }

                        @Bean
                        public Trigger quartzSchedulerScheduledTaskTrigger(JobDetail quartzSchedulerScheduledTaskJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(quartzSchedulerScheduledTaskJobDetail).
                                withIdentity("quartzSchedulerScheduledTaskTrigger").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 */5 * * * ?")).
                                build();
                    }
                    }
                }
                """
            ),
            // Generated AutoConfiguration file
            text(null, EXPECTED_AUTO_CONFIG,
                spec -> spec.path("src/main/java/com/github/rewrite/migration/config/QuartzJobFactoryAutoConfiguration.java")),
            // Generated imports file
            text(null, EXPECTED_AUTO_CONFIG_IMPORTS,
                spec -> spec.path("src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"))
        );
    }

    @Test
    void automaticallyTransformsMethodWithoutTimerParameter() {
        // Methods without Timer parameter ARE also handled - original method kept, Job delegates
        // TimerService injection forces QUARTZ strategy (even without Timer param on method)
        rewriteRun(
            // ScanningRecipe with generate() needs 2 cycles when generating new files
            // Cycle 1: ResolveTimerStrategy adds QUARTZ marker (due to TimerService)
            // Cycle 2: MigrateScheduleToQuartz transforms + generates files
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.annotation.Resource;
                import jakarta.ejb.Schedule;
                import jakarta.ejb.TimerService;

                public class SimpleScheduler {
                    @Resource
                    private TimerService timerService;

                    @Schedule(minute = "0", hour = "8")
                    public void simpleTask() {
                        System.out.println("Running simple task");
                    }
                }
                """,
                """
                import jakarta.annotation.Resource;
                import jakarta.ejb.TimerService;
                import org.quartz.*;
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;

                public class SimpleScheduler {
                    @Resource
                    private TimerService timerService;

                    public void simpleTask() {
                        System.out.println("Running simple task");
                    }

                    public static class SimpleTaskJob implements Job {
                        private final SimpleScheduler delegate;

                        public SimpleTaskJob(SimpleScheduler delegate) {
                            this.delegate = delegate;
                        }

                        @Override
                        public final void execute(JobExecutionContext context) throws JobExecutionException {
                            delegate.simpleTask();
                        }
                    }

                    @Configuration
                    public static class QuartzConfig {

                        @Bean
                        public JobDetail simpleSchedulerSimpleTaskJobDetail() {
                        return
                            JobBuilder.newJob(SimpleTaskJob.class).
                                withIdentity("simpleSchedulerSimpleTaskJobDetail").
                                storeDurably().
                                build();
                    }

                        @Bean
                        public Trigger simpleSchedulerSimpleTaskTrigger(JobDetail simpleSchedulerSimpleTaskJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(simpleSchedulerSimpleTaskJobDetail).
                                withIdentity("simpleSchedulerSimpleTaskTrigger").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 0 8 * * ?")).
                                build();
                    }
                    }
                }
                """
            ),
            // Generated AutoConfiguration file
            text(null, EXPECTED_AUTO_CONFIG,
                spec -> spec.path("src/main/java/com/github/rewrite/migration/config/QuartzJobFactoryAutoConfiguration.java")),
            // Generated imports file
            text(null, EXPECTED_AUTO_CONFIG_IMPORTS,
                spec -> spec.path("src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"))
        );
    }

    @Test
    void transformsWithTimerInfo() {
        // timer.getInfo() with info attribute -> this.timerInfo field
        rewriteRun(
            // ScanningRecipe with generate() needs 2 cycles when generating new files
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.ejb.Schedule;
                import jakarta.ejb.Timer;

                public class InfoScheduler {
                    @Schedule(hour = "12", info = "Daily noon task")
                    public void noonTask(Timer timer) {
                        System.out.println(timer.getInfo());
                    }
                }
                """,
                """
                import org.quartz.*;
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;

                public class InfoScheduler {

                    private final Object timerInfo = "Daily noon task";

                    public void noonTask() {
                        System.out.println(this.timerInfo);
                    }

                    public static class NoonTaskJob implements Job {
                        private final InfoScheduler delegate;

                        public NoonTaskJob(InfoScheduler delegate) {
                            this.delegate = delegate;
                        }

                        @Override
                        public final void execute(JobExecutionContext context) throws JobExecutionException {
                            delegate.noonTask();
                        }
                    }

                    @Configuration
                    public static class QuartzConfig {

                        @Bean
                        public JobDetail infoSchedulerNoonTaskJobDetail() {
                        return
                            JobBuilder.newJob(NoonTaskJob.class).
                                withIdentity("infoSchedulerNoonTaskJobDetail").
                                storeDurably().
                                usingJobData("info", "Daily noon task").
                                build();
                    }

                        @Bean
                        public Trigger infoSchedulerNoonTaskTrigger(JobDetail infoSchedulerNoonTaskJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(infoSchedulerNoonTaskJobDetail).
                                withIdentity("infoSchedulerNoonTaskTrigger").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 0 12 * * ?")).
                                build();
                    }
                    }
                }
                """
            ),
            // Generated AutoConfiguration file
            text(null, EXPECTED_AUTO_CONFIG,
                spec -> spec.path("src/main/java/com/github/rewrite/migration/config/QuartzJobFactoryAutoConfiguration.java")),
            // Generated imports file
            text(null, EXPECTED_AUTO_CONFIG_IMPORTS,
                spec -> spec.path("src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"))
        );
    }

    @Test
    void fallsBackToMarkerForNonLiteralValues() {
        // Non-literal schedule values (constants, field references) -> marker annotation
        // Cycle 1: ResolveTimerStrategy adds QUARTZ marker (non-literals require QUARTZ)
        // Cycle 2: MigrateScheduleToQuartz adds @EjbQuartzSchedule fallback marker
        rewriteRun(
            spec -> spec.expectedCyclesThatMakeChanges(1),
            java(
                """
                import jakarta.ejb.Schedule;

                public class NonLiteralScheduler {
                    public static final String CRON_HOUR = "8";

                    @Schedule(hour = CRON_HOUR, minute = "0")
                    public void configuredTask() {
                        System.out.println("task");
                    }
                }
                """,
                """
                import com.github.migration.annotations.EjbQuartzSchedule;

                public class NonLiteralScheduler {
                    public static final String CRON_HOUR = "8";

                    @EjbQuartzSchedule(rawExpression = "@Schedule(hour = CRON_HOUR, minute = \\"0\\")")
                    public void configuredTask() {
                        System.out.println("task");
                    }
                }
                """
            )
        );
    }

    @Test
    void fallsBackToMarkerForYearAttribute() {
        // @Schedule with year -> marker (Quartz 7-field cron is non-standard)
        // Cycle 1: ResolveTimerStrategy adds QUARTZ marker (year triggers QUARTZ)
        // Cycle 2: MigrateScheduleToQuartz adds @EjbQuartzSchedule fallback marker
        rewriteRun(
            spec -> spec.expectedCyclesThatMakeChanges(1),
            java(
                """
                import jakarta.ejb.Schedule;

                public class YearScheduler {
                    @Schedule(hour = "0", year = "2024")
                    public void yearlyTask() {
                        System.out.println("task");
                    }
                }
                """,
                """
                import com.github.migration.annotations.EjbQuartzSchedule;

                public class YearScheduler {
                    @EjbQuartzSchedule(rawExpression = "@Schedule(hour = \\"0\\", year = \\"2024\\")")
                    public void yearlyTask() {
                        System.out.println("task");
                    }
                }
                """
            )
        );
    }

    @Test
    void fallsBackToMarkerForTimezoneAttribute() {
        // @Schedule with timezone -> marker (requires TZ parsing for Quartz)
        // Cycle 1: ResolveTimerStrategy adds QUARTZ marker (timezone triggers QUARTZ)
        // Cycle 2: MigrateScheduleToQuartz adds @EjbQuartzSchedule fallback marker
        rewriteRun(
            spec -> spec.expectedCyclesThatMakeChanges(1),
            java(
                """
                import jakarta.ejb.Schedule;

                public class TimezoneScheduler {
                    @Schedule(hour = "9", timezone = "America/New_York")
                    public void tzTask() {
                        System.out.println("task");
                    }
                }
                """,
                """
                import com.github.migration.annotations.EjbQuartzSchedule;

                public class TimezoneScheduler {
                    @EjbQuartzSchedule(rawExpression = "@Schedule(hour = \\"9\\", timezone = \\"America/New_York\\")")
                    public void tzTask() {
                        System.out.println("task");
                    }
                }
                """
            )
        );
    }

    @Test
    void transformsMultipleSchedulesToMultipleTriggers() {
        // @Schedules with multiple @Schedule -> multiple Trigger beans (same JobDetail)
        rewriteRun(
            // ScanningRecipe with generate() needs 2 cycles when generating new files
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.ejb.Schedule;
                import jakarta.ejb.Schedules;

                public class MultiScheduler {
                    @Schedules({
                        @Schedule(hour = "8", minute = "0"),
                        @Schedule(hour = "17", minute = "0")
                    })
                    public void twiceDaily() {
                        System.out.println("task");
                    }
                }
                """,
                """
                import org.quartz.*;
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;

                public class MultiScheduler {
                    public void twiceDaily() {
                        System.out.println("task");
                    }

                    public static class TwiceDailyJob implements Job {
                        private final MultiScheduler delegate;

                        public TwiceDailyJob(MultiScheduler delegate) {
                            this.delegate = delegate;
                        }

                        @Override
                        public final void execute(JobExecutionContext context) throws JobExecutionException {
                            delegate.twiceDaily();
                        }
                    }

                    @Configuration
                    public static class QuartzConfig {

                        @Bean
                        public JobDetail multiSchedulerTwiceDailyJobDetail() {
                        return
                            JobBuilder.newJob(TwiceDailyJob.class).
                                withIdentity("multiSchedulerTwiceDailyJobDetail").
                                storeDurably().
                                build();
                    }

                        @Bean
                        public Trigger multiSchedulerTwiceDailyTrigger_1(JobDetail multiSchedulerTwiceDailyJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(multiSchedulerTwiceDailyJobDetail).
                                withIdentity("multiSchedulerTwiceDailyTrigger_1").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 0 8 * * ?")).
                                build();
                    }

                        @Bean
                        public Trigger multiSchedulerTwiceDailyTrigger_2(JobDetail multiSchedulerTwiceDailyJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(multiSchedulerTwiceDailyJobDetail).
                                withIdentity("multiSchedulerTwiceDailyTrigger_2").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 0 17 * * ?")).
                                build();
                    }
                    }
                }
                """
            ),
            // Generated AutoConfiguration file
            text(null, EXPECTED_AUTO_CONFIG,
                spec -> spec.path("src/main/java/com/github/rewrite/migration/config/QuartzJobFactoryAutoConfiguration.java")),
            // Generated imports file
            text(null, EXPECTED_AUTO_CONFIG_IMPORTS,
                spec -> spec.path("src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"))
        );
    }

    @Test
    void transformsSchedulesWithSingleEntry() {
        // @Schedules containing single @Schedule - same as single @Schedule
        rewriteRun(
            // ScanningRecipe with generate() needs 2 cycles when generating new files
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.ejb.Schedule;
                import jakarta.ejb.Schedules;

                public class SingleSchedules {
                    @Schedules(@Schedule(hour = "12"))
                    public void noonTask() {
                        System.out.println("task");
                    }
                }
                """,
                """
                import org.quartz.*;
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;

                public class SingleSchedules {
                    public void noonTask() {
                        System.out.println("task");
                    }

                    public static class NoonTaskJob implements Job {
                        private final SingleSchedules delegate;

                        public NoonTaskJob(SingleSchedules delegate) {
                            this.delegate = delegate;
                        }

                        @Override
                        public final void execute(JobExecutionContext context) throws JobExecutionException {
                            delegate.noonTask();
                        }
                    }

                    @Configuration
                    public static class QuartzConfig {

                        @Bean
                        public JobDetail singleSchedulesNoonTaskJobDetail() {
                        return
                            JobBuilder.newJob(NoonTaskJob.class).
                                withIdentity("singleSchedulesNoonTaskJobDetail").
                                storeDurably().
                                build();
                    }

                        @Bean
                        public Trigger singleSchedulesNoonTaskTrigger(JobDetail singleSchedulesNoonTaskJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(singleSchedulesNoonTaskJobDetail).
                                withIdentity("singleSchedulesNoonTaskTrigger").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 0 12 * * ?")).
                                build();
                    }
                    }
                }
                """
            ),
            // Generated AutoConfiguration file
            text(null, EXPECTED_AUTO_CONFIG,
                spec -> spec.path("src/main/java/com/github/rewrite/migration/config/QuartzJobFactoryAutoConfiguration.java")),
            // Generated imports file
            text(null, EXPECTED_AUTO_CONFIG_IMPORTS,
                spec -> spec.path("src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"))
        );
    }

    @Test
    void keepsTimerImportWhenFallbackMethodUsesTimer() {
        // When one method uses Timer and falls back to marker, keep Timer import
        rewriteRun(
            // ScanningRecipe with generate() needs 2 cycles when generating new files
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.ejb.Schedule;
                import jakarta.ejb.Timer;

                public class MixedScheduler {
                    @Schedule(hour = "8")
                    public void simpleTask() {
                        System.out.println("simple");
                    }

                    @Schedule(hour = "9")
                    public void timerTask(Timer timer) {
                        timer.cancel();
                    }
                }
                """,
                """
                import com.github.migration.annotations.EjbQuartzSchedule;
                import jakarta.ejb.Timer;
                import org.quartz.*;
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;

                public class MixedScheduler {
                    public void simpleTask() {
                        System.out.println("simple");
                    }

                    @EjbQuartzSchedule(rawExpression = "@Schedule(hour = \\"9\\")")
                    public void timerTask(Timer timer) {
                        timer.cancel();
                    }

                    public static class SimpleTaskJob implements Job {
                        private final MixedScheduler delegate;

                        public SimpleTaskJob(MixedScheduler delegate) {
                            this.delegate = delegate;
                        }

                        @Override
                        public final void execute(JobExecutionContext context) throws JobExecutionException {
                            delegate.simpleTask();
                        }
                    }

                    @Configuration
                    public static class QuartzConfig {

                        @Bean
                        public JobDetail mixedSchedulerSimpleTaskJobDetail() {
                        return
                            JobBuilder.newJob(SimpleTaskJob.class).
                                withIdentity("mixedSchedulerSimpleTaskJobDetail").
                                storeDurably().
                                build();
                    }

                        @Bean
                        public Trigger mixedSchedulerSimpleTaskTrigger(JobDetail mixedSchedulerSimpleTaskJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(mixedSchedulerSimpleTaskJobDetail).
                                withIdentity("mixedSchedulerSimpleTaskTrigger").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 0 8 * * ?")).
                                build();
                    }
                    }
                }
                """
            ),
            // Generated AutoConfiguration file
            text(null, EXPECTED_AUTO_CONFIG,
                spec -> spec.path("src/main/java/com/github/rewrite/migration/config/QuartzJobFactoryAutoConfiguration.java")),
            // Generated imports file
            text(null, EXPECTED_AUTO_CONFIG_IMPORTS,
                spec -> spec.path("src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"))
        );
    }

    @Test
    void escapesSpecialCharactersInInfoAttribute() {
        // Info attribute with special characters gets properly escaped
        rewriteRun(
            // ScanningRecipe with generate() needs 2 cycles when generating new files
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.ejb.Schedule;
                import jakarta.ejb.Timer;

                public class EscapeScheduler {
                    @Schedule(hour = "8", info = "Task with \\"quotes\\" and \\\\backslash")
                    public void escapedTask(Timer timer) {
                        System.out.println(timer.getInfo());
                    }
                }
                """,
                """
                import org.quartz.*;
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;

                public class EscapeScheduler {

                    private final Object timerInfo = "Task with \\"quotes\\" and \\\\backslash";

                    public void escapedTask() {
                        System.out.println(this.timerInfo);
                    }

                    public static class EscapedTaskJob implements Job {
                        private final EscapeScheduler delegate;

                        public EscapedTaskJob(EscapeScheduler delegate) {
                            this.delegate = delegate;
                        }

                        @Override
                        public final void execute(JobExecutionContext context) throws JobExecutionException {
                            delegate.escapedTask();
                        }
                    }

                    @Configuration
                    public static class QuartzConfig {

                        @Bean
                        public JobDetail escapeSchedulerEscapedTaskJobDetail() {
                        return
                            JobBuilder.newJob(EscapedTaskJob.class).
                                withIdentity("escapeSchedulerEscapedTaskJobDetail").
                                storeDurably().
                                usingJobData("info", "Task with \\"quotes\\" and \\\\backslash").
                                build();
                    }

                        @Bean
                        public Trigger escapeSchedulerEscapedTaskTrigger(JobDetail escapeSchedulerEscapedTaskJobDetail) {
                        return
                            TriggerBuilder.newTrigger().
                                forJob(escapeSchedulerEscapedTaskJobDetail).
                                withIdentity("escapeSchedulerEscapedTaskTrigger").
                                withSchedule(CronScheduleBuilder.cronSchedule("0 0 8 * * ?")).
                                build();
                    }
                    }
                }
                """
            ),
            // Generated AutoConfiguration file
            text(null, EXPECTED_AUTO_CONFIG,
                spec -> spec.path("src/main/java/com/github/rewrite/migration/config/QuartzJobFactoryAutoConfiguration.java")),
            // Generated imports file
            text(null, EXPECTED_AUTO_CONFIG_IMPORTS,
                spec -> spec.path("src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"))
        );
    }

    @Test
    void fallsBackToMarkerForTimerCancelApi() {
        // timer.cancel() is not auto-transformable -> marker
        // Cycle 1: ResolveTimerStrategy adds QUARTZ marker (Timer param + cancel usage)
        // Cycle 2: MigrateScheduleToQuartz adds @EjbQuartzSchedule fallback marker
        rewriteRun(
            spec -> spec.expectedCyclesThatMakeChanges(2),
            java(
                """
                import jakarta.ejb.Schedule;
                import jakarta.ejb.Timer;

                public class CancelScheduler {
                    @Schedule(hour = "8")
                    public void cancelTask(Timer timer) {
                        timer.cancel();
                    }
                }
                """,
                """
                import com.github.migration.annotations.EjbQuartzSchedule;
                import jakarta.ejb.Timer;

                public class CancelScheduler {
                    @EjbQuartzSchedule(rawExpression = "@Schedule(hour = \\"8\\")")
                    public void cancelTask(Timer timer) {
                        timer.cancel();
                    }
                }
                """
            )
        );
    }
}
